# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_e9USGMPqN7JUdA94A_zWAM_Zxkmu36
"""

import streamlit as st
import pandas as pd
import pickle

# Load the pre-trained SVM model
with open("svm_model.pkl", "rb") as model_file:
    model = pickle.load(model_file)

# Title of the application
st.title("SVM Prediction Application")

# Sidebar for user input
st.sidebar.header("Input Parameters")
st.sidebar.markdown("Please provide input data for prediction below.")

# Input form
def user_input_features():
    Gender = st.sidebar.selectbox("Gender", ("Male", "Female"))
    Age = st.sidebar.slider("Age", 18, 60, 30)
    EstimatedSalary = st.sidebar.slider("Estimated Salary", 15000, 150000, 70000)

    # Convert Gender to numeric
    Gender_numeric = 1 if Gender == "Male" else 0

    # Create input DataFrame
    data = {
        "Gender": Gender_numeric,
        "Age": Age,
        "EstimatedSalary": EstimatedSalary,
    }
    return pd.DataFrame(data, index=[0])

# Get user input
input_df = user_input_features()

# Display user input
st.subheader("User Input")
st.write(input_df)

# Make prediction
if st.button("Predict"):
    prediction = model.predict(input_df)
    result = "Purchased" if prediction[0] == 1 else "Not Purchased"

    # Display prediction result
    st.subheader("Prediction Result")
    st.write(f"The predicted outcome is: **{result}**")

# Footer
st.markdown("---")
st.markdown("Developed as part of Machine Learning Assignment 4, Fall 2024.")

!jupyter nbconvert --to script ap.ipynb

!mv ap.py app.py