# -*- coding: utf-8 -*-
"""Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Inl_V26gS8MPfEYOeP8-VAnHZFW5icGY
"""

import streamlit as st
import pandas as pd
import pickle
from sklearn.svm import SVC

# Title of the Streamlit app
st.title('SVM Model Prediction: Purchase Prediction')

# Input fields for the user
gender_input = st.selectbox('Enter Gender', ['Male', 'Female'])
age_input = st.slider('Enter Age (18-60)', min_value=18, max_value=60, value=30)
salary_input = st.slider('Enter Estimated Salary (15000-150000)', min_value=15000, max_value=150000, value=50000)

# Preprocess user input
gender_numeric = 1 if gender_input.lower() == "male" else 0
input_data = pd.DataFrame({
    "Gender": [gender_numeric],
    "Age": [age_input],
    "EstimatedSalary": [salary_input]
})

# Simulating the SVM model (replace this with actual model loading)
# Normally, you'll load the trained model from the pickle file
# with open('svm_model.pkl', 'rb') as model_file:
#     svm_model = pickle.load(model_file)

# Creating a dummy SVM model for demonstration purposes
svm_model = SVC(kernel="rbf", C=1, gamma=0.1)

# Simulate prediction (replace this with actual model prediction)
prediction = svm_model.predict(input_data)

# Display prediction result
if prediction[0] == 1:
    result = "Purchased"
else:
    result = "Not Purchased"

# Display the result in Streamlit
st.write(f"The predicted outcome is: {result}")