# -*- coding: utf-8 -*-
"""Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Inl_V26gS8MPfEYOeP8-VAnHZFW5icGY
"""

import streamlit as st
import pandas as pd
import pickle
from sklearn.svm import SVC

# Title of the Streamlit app
st.title('SVM Model Prediction: Purchase Prediction')

# Load the dataset (assuming it's a CSV file)
user_data = pd.read_csv('User_Data.csv')  # Adjust this if your file is not in CSV format

# Input fields for the user
gender_input = st.selectbox('Enter Gender', ['Male', 'Female'])
age_input = st.slider('Enter Age (18-60)', min_value=18, max_value=60, value=30)
salary_input = st.slider('Enter Estimated Salary (15000-150000)', min_value=15000, max_value=150000, value=50000)

# Preprocess user input (same as previous)
gender_numeric = 1 if gender_input.lower() == "male" else 0
input_data = pd.DataFrame({
    "Gender": [gender_numeric],
    "Age": [age_input],
    "EstimatedSalary": [salary_input]
})

# Load the trained SVM model from the pickle file
with open('svm_model.pkl', 'rb') as model_file:
    svm_model = pickle.load(model_file)

# Make the prediction using the model
prediction = svm_model.predict(input_data)

# Display prediction result
if prediction[0] == 1:
    result = "Purchased"
else:
    result = "Not Purchased"

# Display the result in Streamlit
st.write(f"The predicted outcome is: {result}")