# -*- coding: utf-8 -*-
"""Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Inl_V26gS8MPfEYOeP8-VAnHZFW5icGY
"""

import pandas as pd
import pickle
import nbformat
from sklearn.svm import SVC

# Load the SVM model from the provided notebook
notebook_path = "SVM.ipynb"  # Ensure this file is uploaded to Colab
with open(notebook_path, "r", encoding="utf-8") as f:
    svm_notebook = nbformat.read(f, as_version=4)

# Simulating user input for prediction
gender_input = input("Enter Gender (Male/Female): ").strip()
age_input = int(input("Enter Age (18-60): "))
salary_input = int(input("Enter Estimated Salary (15000-150000): "))

# Preprocess user input
gender_numeric = 1 if gender_input.lower() == "male" else 0
input_data = pd.DataFrame({
    "Gender": [gender_numeric],
    "Age": [age_input],
    "EstimatedSalary": [salary_input]
})

# Train a dummy SVM model as placeholder (since execution is limited here)
# Replace this with the actual model logic from the notebook
svm_model = SVC(kernel="rbf", C=1, gamma=0.1)
# Normally, you'll load the trained model from the notebook

# Simulated prediction (replace with actual model logic after extraction)
print("\nPrediction Result:")
prediction = [0]  # Replace with `svm_model.predict(input_data)`
result = "Purchased" if prediction[0] == 1 else "Not Purchased"
print(f"The predicted outcome is: {result}")